---
 
 steps:
 # Cloud Build runs the code inside a docker container
 # This is a supported pre-built cloud builder image for docker - stored in Artifact Registry/Google Container Registry - gcr
 
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: [
    'build', 
    '-t', '${_EDUHUB_REPO_LOC}/$PROJECT_ID/${_EDUHUB_REPO}/${_EDUHUB_FRONTEND_IMG}', 
    '-f', 'Dockerfile',
    '.']

 # Push the container image to Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', '${_EDUHUB_REPO_LOC}/$PROJECT_ID/${_EDUHUB_REPO}/${_EDUHUB_FRONTEND_IMG}']
 
 # Deploy container to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args: [
   'run', 'deploy', '${_EDUHUB_CLOUD_RUN_SERVICE}',
   '--image', '${_EDUHUB_REPO_LOC}/$PROJECT_ID/${_EDUHUB_REPO}/${_EDUHUB_FRONTEND_IMG}',
   '--region', 'us-central1',
   '--allow-unauthenticated']

 substitutions:
    _EDUHUB_REPO: eduhub-sdms-repo
    _EDUHUB_FRONTEND_IMG: eduhub-sand-frontend-image:sandpit
    _EDUHUB_CLOUD_RUN_SERVICE: eduhub-sdms-frontend
    _EDUHUB_REPO_LOC: us-central1-docker.pkg.dev

 options:
  logging: CLOUD_LOGGING_ONLY
