---
 
 steps:
 # Cloud Build runs the code inside a docker container
 # This is a supported pre-built cloud builder image for docker - stored in Artifact Registry/Google Container Registry - gcr

 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: [
    'build', 
    '-t', '${_EDUHUB_REPO_LOC}/$PROJECT_ID/${_EDUHUB_REPO}/${_EDUHUB_BACKEND_IMG}', 
    '-f', './${_EDUHUB_BACKEND_DOCKERFILE_PATH}/dockerfile',
    './${_EDUHUB_BACKEND_PATH}']

 # Push the container image to Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', '${_EDUHUB_REPO_LOC}/$PROJECT_ID/${_EDUHUB_REPO}/${_EDUHUB_BACKEND_IMG}']
 
 # Deploy container to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args: [
   'run', 'deploy', '${_EDUHUB_CLOUD_RUN_SERVICE}',
   '--image', '${_EDUHUB_REPO_LOC}/$PROJECT_ID/${_EDUHUB_REPO}/${_EDUHUB_BACKEND_IMG}',
   '--region', 'us-south1',
   '--allow-unauthenticated']

 substitutions:
    _EDUHUB_REPO: eduhub-sdms-repo
    _EDUHUB_BACKEND_IMG: eduhub-sand-backend-image:sandpit
    _EDUHUB_BACKEND_DOCKERFILE_PATH: src
    _EDUHUB_CLOUD_RUN_SERVICE: eduhub-sdms-backend
    _EDUHUB_REPO_LOC: us-south1-docker.pkg.dev

